import { z } from "zod";

export const gameSaveSchema = z.object({
  version: z.literal(1),
  id: z.string(),
  slotId: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  seed: z.number(),
  rngState: z.number(),
  chairmanName: z.string(),
  season: z.number(),
  week: z.number(),
  userClubId: z.string(),
  divisions: z.array(z.any()),
  clubs: z.record(z.string(), z.any()),
  players: z.record(z.string(), z.any()),
  managers: z.record(z.string(), z.any()),
  managerCandidates: z.array(z.any()),
  fixtures: z.array(z.any()),
  currentRound: z.number(),
  lastMatch: z.any().optional(),
  activeProposal: z.any().optional(),
  eventQueue: z.array(z.any()).default([]),
  currentEvent: z.any().optional(),
  seenEventKeys: z.array(z.string()).default([]),
  transferBudget: z.any().optional(),
  pendingDeals: z.array(z.any()).default([]),
  managerRetirementIntent: z.boolean().optional(),
  financialSnapshot: z.any().optional(),
  history: z.array(z.any()),
  achievements: z.array(z.any()),
  hallOfFame: z.array(z.string()),
  settings: z.object({
    sound: z.boolean(),
    textSize: z.enum(["normal", "large"]),
  }),
  gameOver: z.string().optional(),
});
